version: '3.8'

services:
  postgres:
    image: 'postgres:16.8-alpine'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - blog-network
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    image: redis:7.2-alpine
    container_name: blog-redis
    ports:
      - "6379:6379"
    networks:
      - blog-network

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    networks:
      - blog-network
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
    restart: always
    command: [ "java", "-jar", "/app.jar" ]

networks:
  blog-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local