spring:
  application:
    name: blog-app

  datasource:
    url: jdbc:postgresql://blog-app-postgres-1:5432/BlogDB
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: blog-redis
    port: 6379
    enabled: false

server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /

logging:
  level:
    com.codehacks.blog: INFO

jwt:
  expiration-time: 3600000

rate:
  limit:
    requests: 100
    time-window: 2

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

mail:
  host: mail.example.com
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

security:
  team: ${SECURITY_EMAIL}
  email: ${TEAM_EMAIL}
  known-ips:
    - 192.168.1.100
    - 192.168.1.101
