name: Test Docker Login

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  test-login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
          if [ -z "$DOCKER_USERNAME" ]; then
            echo "❌ DOCKER_USERNAME is empty"
            exit 1
          else
            echo "✅ DOCKER_USERNAME is set"
          fi
          if [ -z "$DOCKER_PASSWORD" ]; then
            echo "❌ DOCKER_PASSWORD is empty"
            exit 1
          else
            echo "✅ DOCKER_PASSWORD is set"
          fi

      - name: Test Docker Login
        run: |
          echo "Attempting Docker login..."
          if ! echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; then
            echo "❌ Docker login failed"
            exit 1
          fi
          echo "✅ Successfully logged in to Docker Hub"
          
          # Test pulling a public image to verify login
          echo "Testing image pull..."
          docker pull hello-world
          docker run hello-world
