name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
#      - '**'  # Match all branches

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t blog-app .
