name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '**'  # Match all branches

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t blog-app .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag blog-app ${{ secrets.DOCKER_USERNAME }}/blog-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/blog-app:latest

      - name: Debug
        run: |
          echo "Docker version:"
          docker --version
          echo "Attempting Docker login..."
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"