name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '**'  # Match all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean package  # Runs in the root directory where pom.xml is located

      - name: Build Docker image
        run: docker build -t blog-app .  # Use the root Dockerfile

      - name: Login to Docker Hub
#        run: echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag blog-app rume7/blog-app:latest
          docker push rume7/blog-app:latest

