name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '**'  # Match all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean package  # Runs in the root directory where pom.xml is located

      - name: Build Docker image
        run: docker build -t blog-backend .  # Use the root Dockerfile

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag blog-backend rume7/blog-backend:latest
          docker push rume7/blog-backend:latest

