name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '**'  # Match all branches

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t blog-app .

      - name: Login to Docker Hub
        run: |
              echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag blog-app $DOCKER_USERNAME/blog-app:latest
          docker push $DOCKER_USERNAME/blog-app:latest